# Generated by Django 4.0 on 2021-12-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_alter_comment_avatar_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.JSONField(),
        ),
    ]
